# Generated by Django 5.2.3 on 2025-07-09 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesProyecto',
            fields=[
                ('idactividad', models.AutoField(db_column='idActividad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividades_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlineacionObjetivoOds',
            fields=[
                ('idobjods', models.AutoField(db_column='idObjOds', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alineacion_objetivo_ods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditDetalle',
            fields=[
                ('idauddetalle', models.AutoField(db_column='idAudDetalle', primary_key=True, serialize=False)),
                ('nombrecampo', models.CharField(blank=True, db_column='nombreCampo', max_length=255, null=True)),
                ('oldvalue', models.CharField(blank=True, db_column='oldValue', max_length=255, null=True)),
                ('newvalue', models.CharField(blank=True, db_column='newValue', max_length=255, null=True)),
            ],
            options={
                'db_table': 'audit_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('idauditlog', models.AutoField(db_column='idAuditLog', primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=50, null=True)),
                ('modulo', models.CharField(blank=True, max_length=150, null=True)),
                ('idobjeto', models.IntegerField(blank=True, db_column='idObjeto', null=True)),
                ('strobjeto', models.CharField(blank=True, db_column='strObjeto', max_length=255, null=True)),
                ('ipaddress', models.CharField(blank=True, db_column='ipAddress', max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('audfecha', models.DateTimeField(blank=True, db_column='audFecha', null=True)),
                ('auth_source', models.CharField(db_comment='Si viene de LDAP o de Django la autenticación', max_length=255)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cantones',
            fields=[
                ('idcanton', models.AutoField(db_column='idCanton', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cantones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('idindicador', models.AutoField(db_column='idIndicador', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('formula', models.IntegerField(blank=True, null=True)),
                ('unidadmedida', models.CharField(blank=True, db_column='unidadMedida', max_length=255, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'indicadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('idmeta', models.AutoField(db_column='idMeta', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipometa', models.CharField(blank=True, db_column='tipoMeta', max_length=255, null=True)),
                ('idusuario', models.IntegerField(blank=True, db_column='idUsuario', null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('idobjest', models.AutoField(db_column='idObjEst', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(db_column='fechaRegistro')),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'objetivo_estrategico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEstrategicoHistory',
            fields=[
                ('idobjesth', models.AutoField(db_column='idObjEstH', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fechainicio', models.DateTimeField(blank=True, db_column='fechaInicio', null=True)),
                ('fechafin', models.DateTimeField(blank=True, db_column='fechaFin', null=True)),
                ('numversion', models.IntegerField(db_column='numVersion')),
                ('cambiadoporusr', models.IntegerField(blank=True, db_column='cambiadoPorUsr', null=True)),
                ('fechacambio', models.DateTimeField(db_column='fechaCambio')),
                ('idpnd', models.IntegerField(blank=True, db_column='idPnd', null=True)),
            ],
            options={
                'db_table': 'objetivo_estrategico_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjetivosDesarrolloSostenible',
            fields=[
                ('idods', models.AutoField(db_column='idOds', primary_key=True, serialize=False)),
                ('numeroods', models.IntegerField(blank=True, db_column='numeroOds', null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'objetivos_desarrollo_sostenible',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parroquias',
            fields=[
                ('idparroquia', models.AutoField(db_column='idParroquia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'parroquias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoActividad',
            fields=[
                ('idperiodo', models.AutoField(db_column='idPeriodo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periodo_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('idplan', models.AutoField(db_column='idPlan', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('nivaut', models.IntegerField(blank=True, db_column='nivAut', null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanNacionalDesarrollo',
            fields=[
                ('idpnd', models.AutoField(db_column='idPnd', primary_key=True, serialize=False)),
                ('nombreeje', models.CharField(db_column='nombreEje', max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan_nacional_desarrollo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('idprograma', models.AutoField(db_column='idPrograma', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaprograma', models.DateTimeField(blank=True, db_column='fechaPrograma', null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'programas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('idprovincia', models.AutoField(db_column='idProvincia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'provincias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoHistory',
            fields=[
                ('idproyectoh', models.AutoField(db_column='idProyectoH', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fechainicio', models.DateTimeField(blank=True, db_column='fechaInicio', null=True)),
                ('fechafin', models.DateTimeField(blank=True, db_column='fechaFin', null=True)),
                ('numversion', models.IntegerField(blank=True, db_column='numVersion', null=True)),
                ('cambiadoporusr', models.IntegerField(blank=True, db_column='cambiadoPorUsr', null=True)),
                ('fechacambio', models.DateTimeField(blank=True, db_column='fechaCambio', null=True)),
                ('idiambiental', models.IntegerField(blank=True, db_column='idIAmbiental', null=True)),
                ('idinstitucion', models.IntegerField(blank=True, db_column='idInstitucion', null=True)),
                ('idug', models.IntegerField(blank=True, db_column='idUG', null=True)),
                ('situacionactual', models.CharField(blank=True, db_column='situacionActual', max_length=1000, null=True)),
                ('antecedente', models.CharField(blank=True, max_length=500, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=500, null=True)),
                ('beneficiarios', models.CharField(blank=True, max_length=255, null=True)),
                ('proyectosrelacionados', models.CharField(blank=True, db_column='proyectosRelacionados', max_length=255, null=True)),
                ('idobjest', models.IntegerField(blank=True, db_column='idObjEst', null=True)),
                ('idmeta', models.IntegerField(blank=True, db_column='idMeta', null=True)),
                ('inversion', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('duracionproyecto', models.DecimalField(blank=True, db_column='duracionProyecto', decimal_places=65535, max_digits=65535, null=True)),
                ('autogestion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyecto_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoImpactoAmbiental',
            fields=[
                ('idiambiental', models.AutoField(db_column='idIAmbiental', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyecto_impacto_ambiental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('idproyecto', models.AutoField(db_column='idProyecto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('situacionactual', models.CharField(blank=True, db_column='situacionActual', max_length=1000, null=True)),
                ('antecedente', models.CharField(blank=True, max_length=500, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=500, null=True)),
                ('beneficiarios', models.CharField(blank=True, max_length=255, null=True)),
                ('proyectosrelacionados', models.CharField(blank=True, db_column='proyectosRelacionados', max_length=255, null=True)),
                ('inversion', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('duracionproyecto', models.DecimalField(blank=True, db_column='duracionProyecto', decimal_places=65535, max_digits=65535, null=True)),
                ('autogestion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoUbiGeografica',
            fields=[
                ('idug', models.AutoField(db_column='idUG', primary_key=True, serialize=False)),
                ('coordenadas', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'proyecto_ubi_geografica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstitucionSector',
            fields=[
                ('idsector', models.AutoField(db_column='idSector', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'institucion_sector',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('idpermiso', models.AutoField(db_column='idPermiso', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permisos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idrol', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstitucionSubsector',
            fields=[
                ('idsubsector', models.AutoField(db_column='idSubsector', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField()),
                ('idsector', models.ForeignKey(blank=True, db_column='idSector', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_sipeip.institucionsector')),
            ],
            options={
                'db_table': 'institucion_subsector',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('idinstitucion', models.AutoField(db_column='idInstitucion', primary_key=True, serialize=False)),
                ('idsector', models.IntegerField(db_column='idSector')),
                ('nombre', models.CharField(max_length=255)),
                ('nivelgobierno', models.CharField(db_column='nivelGobierno', max_length=255)),
                ('estado', models.BooleanField()),
                ('fechacreacion', models.DateTimeField(db_column='fechaCreacion')),
                ('fechaactualizacion', models.DateTimeField(blank=True, db_column='fechaActualizacion', null=True)),
                ('idsubsector', models.ForeignKey(db_column='idSubSector', on_delete=django.db.models.deletion.DO_NOTHING, to='app_sipeip.institucionsubsector')),
            ],
            options={
                'db_table': 'instituciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('identificacion', models.CharField(blank=True, max_length=13, null=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='fechaCreacion', null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('idpermiso', models.ForeignKey(blank=True, db_column='idPermiso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_sipeip.permisos')),
                ('idrol', models.ForeignKey(blank=True, db_column='idRol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_sipeip.roles')),
                ('user', models.OneToOneField(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
    ]
